### ISSUE TITLE
Cardinal-bin build dosen't work 

### ISSUE THREAD

**Issue by Inqb8tr-jp** [mod-audio/mod-plugin-builder#189]
I don't know a procedure I take to build cardinal-bin for MOD Desktop is correct or not,  but I can build Cardinal.lv2, CardinalFX.lv2 and CardinalMini.lv2 without errors.

But the plugins I build don't work.

The procedure I take is below.
1. Download  Cardinal-linux-x86_64-24.09.tar.gz and extract.
2. make a directory structure named binaries/x86_64 including Cardinal.so, CardinalFX.so and CardinalMini_dsp.so
3. compress it with tar.xz.
4. put binaries.tar.xz to mod_plugin_builder/plugins/packages/cardinal-bin/
5. copy CardinalFX.lv2, Cardinal.lv2 and CardinalMini.lv2 to mod_plugin_builder/plugins/packages/cardinal-bin/bundles/
6. build with "MOD_BIN_COMPAT=x86_64 ./build generic-x86_64 cardinal-bin"

Am I doing something wrong in the process?

I use the plugins on MOD Desktop ver 0.0.12.

**Comment by falkTX** [comment]
there is no need to repackage the plugins, the cardinal-bin is just for convenience for uploading things to the store.

why the plugins dont work I dont know, I didnt try cardinal on the mod-desktop yet. but it is not an issue with the plugin builder, issue is somewhere else.
first see if the plugins work at all in general, in a regular daw. then try them on mod-desktop.

I am closing the ticket since it is unrelated to plugin builder.
